<a href="https://colab.research.google.com/github/Hefot-Ahmed/Machine-Learning-/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install torch

import torch

x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [3]:
x = torch.tensor([[1,2],[3,4]])
print(x)

tensor([[1, 2],
        [3, 4]])


In [4]:
x = torch.tensor([[1,2],[3,4]])

print(x.shape)

torch.Size([2, 2])


In [7]:
torch.zeros(3)

tensor([0., 0., 0.])

In [8]:
torch.ones(3)

tensor([1., 1., 1.])

In [9]:
torch.rand(3)

tensor([0.2100, 0.2230, 0.0561])

In [11]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a + b)
print(a * b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [12]:
import torch

a = torch.tensor([2,4,6])
b = torch.tensor([1,3,5])

result = a + b

print(result)

tensor([ 3,  7, 11])


In [13]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x**3

y.backward()

print(x.grad)

tensor(12.)


In [14]:
import torch
import torch.nn as nn

layer = nn.Linear(2,1)

x = torch.tensor([3.0,4.0])

y = layer(x)

print(y)

tensor([2.5052], grad_fn=<ViewBackward0>)


In [19]:
import torch
import torch.nn as nn

class MyNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(1,3)

        self.layer2 = nn.Linear(3,1)

    def forward(self, x):

        x = self.layer1(x)

        x = torch.relu(x)

        x = self.layer2(x)

        return x

model = MyNet()

x = torch.tensor([2.0])

print(model(x))

tensor([-1.5341], grad_fn=<ViewBackward0>)


In [1]:
import torch
from torch.utils.data import DataLoader, TensorDataset

X = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[2.0],[4.0],[6.0],[8.0]])

dataset = TensorDataset(X, y)

loader = DataLoader(dataset, batch_size=2, shuffle=True)

for batch_X, batch_y in loader:

    print(batch_X, batch_y)

tensor([[3.],
        [2.]]) tensor([[6.],
        [4.]])
tensor([[1.],
        [4.]]) tensor([[2.],
        [8.]])


In [2]:
import torch
import torch.nn as nn

conv = nn.Conv2d(1,2,3)

image = torch.randn(1,1,8,8)

output = conv(image)

print(output.shape)

torch.Size([1, 2, 6, 6])
